version: 2
jobs:
  build_and_test:
    working_directory: /app # ~/repo
    docker:
      - image: google/cloud-sdk  # docker:17.05.0-ce-git
    environment:
      GOOGLE_PROJECT_ID: 'ai-sg-workshop'
      GOOGLE_COMPUTE_ZONE: 'asia-southeast1-a'
      IMAGE_NAME: 'ci-workshop-app'
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/my-docker-image.tar
      - run:
          name: Load Docker image layer cache
          command: docker load -i /caches/my-docker-image.tar || true
      - run:
          name: Build application Docker image (without ML model)
          command: docker build . -t ci-workshop-app:base --cache-from=ci-workshop-app --target Base
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/my-docker-image.tar ci-workshop-app:base
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/my-docker-image.tar
      - run:
          name: run unit tests
          command: docker run ci-workshop-app:base bin/test.sh
      - run:
          name: Build application Docker image (with ML model)
          command: docker build . -t ci-workshop-app:build --cache-from=ci-workshop-app:base --target Build
      - run:
          name: run model metrics tests
          command: docker run ci-workshop-app:build bin/test_model_metrics.sh
      - run: 
          name: setup google cloud SDK + authenticate
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud auth configure-docker
      - run:
          name: push artifact to container registry
          command: |
            docker tag ci-workshop-app:build asia.gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME:$CIRCLE_SHA1
            docker push asia.gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME:$CIRCLE_SHA1
  deploy_to_gcp:
    docker:
      - image: google/cloud-sdk
        environment:
          GOOGLE_PROJECT_ID: ai-sg-workshop
          GOOGLE_COMPUTE_ZONE: asia-southeast1-a
          deployment_name: 'ci-workshop-app-deployment'
          image_name: 'ci-workshop-app'
    steps:
      - checkout
      - attach_workspace:
          at: /caches
      - run: 
          name: setup google cloud SDK + authenticate
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud auth configure-docker
      - setup_remote_docker
      - run:
          name: Deploy image to kubernetes
          command: |
            # authenticate
            gcloud container clusters get-credentials my-cluster --region asia-southeast1
            # deploy new image
            kubectl set image deployment/$deployment_name $image_name=asia.gcr.io/$GOOGLE_PROJECT_ID/$image_name:$CIRCLE_SHA1

workflows:
  version: 2
  my_ci_pipeline:
    jobs:
      - build_and_test
      - deploy_to_gcp:
          requires:
            - build_and_test