version: 2
jobs:
  hello_world:
    working_directory: ~/repo 
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: hello ai.sg
          command: echo "hello ai singapore"

workflows:
  version: 2
  my_ci_pipeline:
    jobs:
      - hello_world