# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2
jobs:
  train_and_test:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/.venv
            source ~/.venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ~/.venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run unit tests
          command: |
            source ~/.venv/bin/activate
            bin/test.sh
      - run:
          name: train model
          command: |
            source ~/.venv/bin/activate
            python train.py
      - run:
          name: run model metrics tests
          command: echo "skipping metrics tests for now"
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy_staging:
    docker:
      - image: google/cloud-sdk
        environment:
          GOOGLE_PROJECT_ID: ai-sg-workshop
          GOOGLE_COMPUTE_ZONE: asia-southeast1-a
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: setup google cloud SDK
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud auth configure-docker
      - setup_remote_docker
      - run: 
          name: build docker image
          command: |
            docker build . -t asia.gcr.io/ai-sg-workshop/my-app:$CIRCLE_SHA1
      - run:
          name: push artifact
          command: |
            docker push asia.gcr.io/ai-sg-workshop/my-app:$CIRCLE_SHA1
      - run:
          name: deploy app
          command: gcloud --quiet app deploy --image-url=asia.gcr.io/ai-sg-workshop/my-app:$CIRCLE_SHA1

workflows:
  version: 2
  my_ci_pipeline:
    jobs:
      - train_and_test
      - deploy_staging:
          requires:
            - train_and_test